name: Run JMeter Test

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "master" branch
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "jmeter-test"
    jmeter-test:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v4

        # Runs a set of commands using the runners shell
        - name: Install Python, Java Runtime and Taurus
            run: |
                sudo apt update
                sudo apt install python3 default-jre-headless python3-tk python3-pip python3-dev libxml2-dev libxslt-dev zlib1g-dev net-tools
                sudo python3 -m pip install bzt

        # Runs a single command using the runners shell
        - name: Run JMeter Test
            run: bzt test.jmx